pkgit-find-repo-root can optionally be given a starting directory. More error checking.

diff --git a/scripts/pkgit b/scripts/pkgit
--- a/scripts/pkgit
+++ b/scripts/pkgit
@@ -219,7 +219,7 @@ mkdir -p $rpmhome  || die "Could not make the $rpmhome directory"
 cd $rpmhome  >/dev/null 
 rpmdev-setuptree  || die "Failed to create the expected rpmbuild expected directory structure"
 
-pkgit-create-tarball $verbose --project-dir="$current_specfile_path" --tag-name="$tag_name"
+pkgit-create-tarball $debug $verbose --project-dir="$current_specfile_path" --tag-name="$tag_name" || die "Failed creating tarball"
 
 # build RPM
 verbose_echo "Building RPM with rpmbuild"
@@ -227,7 +227,8 @@ cd $rpmhome/SPECS  >/dev/null
 if [ -z $verbose ]; then
     QUIET_FLAG=--quiet
 fi
-rpmbuild --clean $QUIET_FLAG -ba $(basename $spec)
+
+rpmbuild --clean $QUIET_FLAG -ba $(basename $spec) || die "Failed in rpmbuild"
 cd $rpmhome >/dev/null
 
 # move the newly built rpms to the project directory
diff --git a/test/run-all-tests b/test/run-all-tests
--- a/test/run-all-tests
+++ b/test/run-all-tests
@@ -20,7 +20,7 @@ test_packaging()
 {
     git push >/dev/null 2>&1
     git clean -x -d -f >/dev/null
-    pkgit 
+    pkgit --quiet || die "pkgit failed"
     if [ $(ls *rpm |wc -l) != 3 ]; then
         die "Failure creating rpms for project $1.  Should have been an rpm, debug rpm and a source rpm created."
     fi
@@ -179,5 +179,5 @@ fi
 
 
 # Cleanup
-#rm -rf $top_working_dir >/dev/null 2>&1
+rm -rf $top_working_dir >/dev/null 2>&1
 PATH="$ORIGPATH"
