Fixed bug in pkgit-tag-next that assigned incorrect tag numbers on occasion.  pkgit can now rollback and republish an old tag.

diff --git a/scripts/pkgit b/scripts/pkgit
--- a/scripts/pkgit
+++ b/scripts/pkgit
@@ -1,7 +1,6 @@
 #!/usr/bin/env dash
 
 # Publish a package using the spec file in the current directory
-
 umask 0002
 
 usage()
@@ -58,7 +57,7 @@ while true; do
         "-p"|"--pretend"  )  pretend="--pretend" ;;
         "-m"|"--message"  )  shift; message="$1" ;;
         "--"              )  shift ; break ;;
-        *                 )  echo >&2 "getopt error!" ; exit 1 ;;
+        *                 )  die "getopt error!" ; exit 1 ;;
     esac
     shift
 done
@@ -76,10 +75,13 @@ if [ $? != 0 ]; then
     die "Cannot run this script outside of a git repository"
 fi
 
-# Refuse to package if we aren't on branch master.  May remove this limitation in the future
+# Refuse to package if we aren't on branch master and there isn't an exact tag describing the sha1.  May remove this limitation in the future
 current_branch=$(git branch |grep '*'|cut -d' ' -f2)
 if [ $current_branch != "master" ]; then
-    die "Refusing to publish: not on branch master.  Try 'git checkout master' before using pkgit again"
+    exact_tag=$(git describe --tags --match='*-*.*.*-*' --exact 2>/dev/null)
+    if [ $? != 0 ]; then
+        die "Refusing to publish: not on branch master and no exact tag describing where we are.  Try 'git checkout master' before using pkgit again"
+    fi
 fi
 
 # Refuse to package if there are untracked files (if .gitignore knows about them then it is OK to proceed)
@@ -192,34 +194,35 @@ fi
 verbose_echo "Building in $top_level_build_dir"
 rpmhome=$top_level_build_dir/rpmbuild
 mkdir -p $rpmhome
-cd $rpmhome
+cd $rpmhome  >/dev/null 
 rpmdev-setuptree
 
 
 # rpmbuild expects to find the files in a tarball with the package-version as the top level directory.
 # We build up the expected tarball by going through a temporary symlink.
+verbose_echo "Building tarball"
 mkdir -p $rpmhome/tmp
-cd $rpmhome/tmp
+cd $rpmhome/tmp   >/dev/null 
 ln -s $current_specfile_path $rpmhome/tmp/${tag_name%-*}
-find -L . -type f 2>/dev/null | perl -n -e 'print unless m!(/\.git/|.gitignore)!'  > $rpmhome/${spec}_files_to_tar.txt
-
+find -L . -type f 2>/dev/null | perl -n -e 'print unless m!(/\.git/|.gitignore)!'  > $rpmhome/${spec}_files_to_tar.txt 
 tar -cvzf $rpmhome/SOURCES/${tag_name%-*}.tgz --files-from $rpmhome/${spec}_files_to_tar.txt >/dev/null  2>&1
 
-cd $rpmhome
+cd $rpmhome  >/dev/null 
 rm ${spec}_files_to_tar.txt
 rm -rf $rpmhome/tmp
 
-cp $current_specfile_path/$spec $rpmhome/SPECS
-
 # build RPM
-cd $rpmhome/SPECS  >/dev/null || exit 1
-rpmbuild -ba $(basename $spec) || exit 1
-cd $rpmhome
-find -name "*.rpm" -exec mv {} $current_specfile_path \;
+verbose_echo "Building RPM"
+cp $current_specfile_path/$spec $rpmhome/SPECS
+cd $rpmhome/SPECS  >/dev/null
+rpmbuild --clean --quiet -ba $(basename $spec)
+cd $rpmhome >/dev/null
+find -name "*.rpm" -exec mv {} $current_specfile_path \;  >/dev/null
 
 # reset the spec file
-cd $current_specfile_path
-git checkout $spec
+verbose_echo "Cleaning up"
+cd $current_specfile_path  >/dev/null
+git checkout $spec >/dev/null
 rm -rf $rpmhome/*
 
 
diff --git a/scripts/pkgit-tag-next b/scripts/pkgit-tag-next
--- a/scripts/pkgit-tag-next
+++ b/scripts/pkgit-tag-next
@@ -42,6 +42,12 @@ EOF
 exit 0
 }
 
+die()
+{
+    echo >&2 "$@"
+    exit 1
+}
+
 verbose_echo()
 {
     if [ -n "$verbose" ]; then
@@ -80,13 +86,13 @@ fi
 
 package="$1"
 
-# Ensure we are on the master branch
-current_branch=$(git branch | grep '*' |cut -f2 -d' ') 
-if [ "master" != "$current_branch" ]; then
-    echo >&2 "Cannot automatically create a version number unless it is on the master branch."
-    echo >&2 "You should manually assign a tag by incrementing the release number on the version you branched."
-    echo >&2 "Current branch : " $current_branch 
-    exit 1
+# Ensure we are on the master branch or that there is already an exact tag for the sha1
+current_branch=$(git branch |grep '*'|cut -d' ' -f2)
+if [ $current_branch != "master" ]; then
+    exact_tag=$(git describe --tags --match='*-*.*.*-*' --exact 2>/dev/null)
+    if [ $? != 0 ]; then
+        die "Cannot automatically create a new version number unless repo is on the master branch."      
+    fi
 fi
 
 # Make sure the tags are up to date with the central repo
@@ -110,7 +116,7 @@ else
     # Need to be a little careful when a tag of the form blah-blah-blah also points to the same sha1 as mypkg-2.5.4-1
     # git rev-list will find the lastest sha1 with a tag of the form mypkg-2.5.4-1, the use git tag to convert the sha1 to a tag, then slice and dice the tag to get the version-release
     # Can't use git describe rather than git tag as describe will happily hand back the blah-blah-blah tag.
-    greatest_version=$(git tag -l  '*-*.*.*-*' --contains=$(git rev-list --tags='*-*.*.*-*' --max-count=1) | head -1 | rev | cut -d- -f-2 |rev)
+    greatest_version=$(git tag -l  '*-*.*.*-*' --contains=$(git rev-list --date-order --tags='*-*.*.*-*' --max-count=1) | head -1 | rev | cut -d- -f-2 |rev)
     variables=$(echo $greatest_version | sed 's%\([0-9].*\)\.\([0-9].*\)\.\([0-9].*\)-\([0-9]\)%major=\1;minor=\2;revision=\3;release=\4%')    
     eval $variables    
     revision=$(($revision + 1))
